Add navbar link for success stories
peviitor-ro/oportunitatisicariere pull request #530
Opened 2024-12-21 18:06 UTC by porobertdev

Closes #527

2024-12-22 20:01 UTC, AdelinaMoroaca commented
please check and correct:  
 - the nav links must work for all pages( for example the routing from details and 404 nav pages are not working as expected )
 - the responsive UI nav
![image](https://github.com/user-attachments/assets/72e5e856-1d82-4033-9896-96270a25cad6)

2025-01-12 12:21 UTC, porobertdev commented
@AdelinaMoroaca  Can you review the new changes? Keep in mind the PR was done the "old way" back then.

2025-01-12 16:33 UTC, AdelinaMoroaca requested changes
change brakepoint 1160px to 1280px;
remove from _header.scss  ~ line 416   margin-left: 4rem;

2025-01-12 19:27 UTC, AdelinaMoroaca approved these changes

2025-01-12 19:27 UTC, merged